# Generated by Django 6.1.1 on 2026-10-07 22:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopreco',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardware.componente'),
        ),
        migrations.AlterField(
            model_name='historicopreco',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardware.loja'),
        ),
        migrations.AlterField(
            model_name='historicopreco',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='historicopreco',
            constraint=models.UniqueConstraint(fields=('componente', 'loja', 'data_coleta'), name='preco_unico_por_peca_loja_dia'),
        ),
    ]
